# After TC11

sortDropdown=//select[@data-test='product-sort-container']
productPrice=//div[@class='inventory_item_price']
productName=//div[@class='inventory_item_name']
productItem=//div[@class='inventory_item']
